import React from 'react';

const movieList = () => {
  const list = [
  	"12 Angry Men",
    "The Green Mile",
    "The Lord of the Rings: The Return of the King",
    "The Shawshank Redemption",
    "Memento",
    "Se7en",
    "The Dark Knight",
    "Trainspotting",
    "Inception",
    "Once Upon a Time in the West",
    "American History X",
    "Shutter Island",
    "Pulp Fiction",
    "The Matrix",
    "Schindler's List",
    "Good Will Hunting",
    "Django Unchained",
    "It's A Wonderful Life",
    "Toy Story",
    "Inglourious Basterds",
    "Whiplash",
    "2001: A Space Odyssey",
    "Fight Club",
    "Logan",
    "The Shining",
    "Carlito's Way",
    "American Beauty",
    "Star Wars: Episode IV",
    "Rocky IV",
    "Yojimbo",
    "Star Wars: Episode V",
    "Rocky III",
    "The Thing",
    "Rocky II",
    "Indiana Jones and The Last Crusade",
    "Prisoners",
    "The Hurricane",
    "Braveheart",
    "One Flew Over the Cuckoo's Nest",
    "Million Dollar Baby",
    "Unforgiven",
    "Vertigo",
    "Misery",
    "Chinatown",
    "Dog Day Afternoon",
    "Avengers: Infinity War",
    "Léon: The Professional",
    "Star Wars: Episode VI - Return of the Jedi",
    "Parasite",
    "Hot Fuzz",
    "Kill Bill: Volume 1",
    "The Game",
    "City of God",
    "Casino",
    "The Intouchables",
    "Birdman or (The Unexpected Virtue of Ignorance)",
    "Rocky",
    "Halloween",
    "Close Encounters of the Third Kind",
    "The Raid: Redemption",
    "Deadpool",
    "Nightcrawler",
    "The Departed",
    "Gran Torino",
    "The Social Network",
    "The Good, the Bad and the Ugly",
    "Philadelphia",
    "The Lord of the Rings: The Fellowship of the Ring",
    "Die Hard with a Vengeance",
    "Batman Begins",
    "V for Vendetta",
    "Full Metal Jacket",
    "Planet of the Apes",
    "Back to the Future",
    "X-Men: Days of Future Past",
    "Catch Me If You Can",
    "Gone Girl",
    "Donnie Darko",
    "The Sixth Sense",
    "The Lord of the Rings: The Two Towers",
    "Predator",
    "Spotlight",
    "Ratatouille",
    "X-Men: First Class",
    "Toy Story 2",
    "The Bourne Ultimatum",
    "Heat",
    "The Truman Show",
    "The Prestige",
    "Joker",
    "The Last Samurai",
    "Almost Famous",
    "Dirty Harry",
    "Magnum Force",
    "Ocean's Eleven",
    "Seven Samurai",
    "Rambo: First Blood",
    "The Godfather: Part II",
    "The Grand Budapest Hotel",
    "Alien",
    "The Falcon and the Winter Soldier",
    "Thunder Force",
    "Mortal Kombat",
    "Godzilla vs. Kong",
    "Nobody",
    "Army of the Dead",
    "F9",
    "Zack Snyder's Justice League",
    "Love and Monsters",
    "The New Mutants",
    "The Marksman",
    "Those Who Wish Me Dead",
    "The Suicide Squad",
    "Chaos Walking",
    "The Hitman's Wife's Bodyguard",
    "Raya and the Last Dragon",
    "Demon Slayer the Movie: Mugen Train",
    "Spider-Man: Into the Spider-Verse",
    "The Incredibles",
    "Mortal Kombat Legends: Scorpion's Revenge",
    "How to Train Your Dragon",
    "Big Hero 6",
    "Vinland Saga",
    "Incredibles 2",
    "Princess Mononoke",
    "Kingsglaive: Final Fantasy XV",
    "Kung Fu Panda",
    "How to Train Your Dragon: The Hidden World",
    "Mank",
    "Judas and the Black Messiah",
    "The Big Bull",
    "The Wolf of Wall Street",
    "The Dig",
    "The Greatest Showman",
    "Bohemian Rhapsody",
    "Goodfellas",
    "Madame Claude",
    "Green Book",
    "Everest",
    "Hamilton",
    "Moneyball",
    "The Pianist",
    "Scam 1992: The Harshad Mehta Story",
    "Ford v Ferrari",
    "Ammonite",
    "The United States vs. Billie Holiday",
    "Hacksaw Ridge",
    "The Irishman",
    "City of Lies",
    "Rush",
    "Bombshell",
    "Into the Wild",
    "The Big Short",
    "Palm Springs",
    "Happy Gilmore",
    "Another Round",
    "The Stand In",
    "I Care a Lot",
    "Riders of Justice",
    "The Serpent",
    "Promising Young Woman",
    "Sleepers",
    "Night in Paradise",
    "The Woman in the Window",
    "Cruella",
    "The Father",
    "Nomadland",
    "Sound of Metal",
    "The Little Rascals",
    "Soul",
    "Harry Potter and the Sorcerer's Stone",
    "Harry Potter and the Half-Blood Prince",
    "Space Jam: A New Legacy",
    "Tom and Jerry",
    "The Goonies",
    "The Mighty Ducks",
    "Harry Potter and the Deathly Hallows: Part 1",
    "Yes Day",
    "Wolfwalkers",
    "A Week Away",
    "Mulan",
    "Stardust",
    "Shrek 2",
    "The Princess Bride",
    "Harry Potter and the Goblet of Fire",
    "D2: The Mighty Ducks",
    "Shrek",
    "The Sandlot",
    "The Lion King",
    "The Croods: A New Age",
    "Moana",
    "Home Alone",
    "The Girl Who Believes in Miracles",
    "My Fair Lady",
    "Spirited Away",
    "Harry Potter and the Chamber of Secrets",
    "Night at the Museum",
    "Space Jam",
    "Zootopia",
    "The NeverEnding Story",
    "The Witches",
    "Wonder Woman 1984",
    "Godzilla: King of the Monsters",
    "Harry Potter and the Deathly Hallows: Part 2",
    "Justice League",
    "Kong: Skull Island",
    "Monster Hunter",
    "Thor: Ragnarok",
    "What Lies Below",
    "The Unholy",
    "Midsommar",
    "Willy's Wonderland",
    "Roohi",
    "In the Earth",
    "Dawn of the Dead",
    "Alien: Covenant",
    "The Power",
    "The Invisible Man",
    "Jakob's Wife",
    "Scream",
    "Spiral",
    "Dracula",
    "Us"
  ]
  return list;
};

export default movieList;

  
