import React from 'react';

const movieList = () => {
  const list = [
  	"12 Angry Men",
    "The Green Mile",
    "The Lord of the Rings: The Return of the King",  
    "The Shawshank Redemption",  
    "Memento",  
    "Se7en",  
    "The Dark Knight",  
    "Trainspotting",
    "Inception",  
    "Once Upon a Time in the West", 
    "American History X",  
    "Shutter Island",  
    "Pulp Fiction",  
    "The Matrix",  
    "Schindler's List",  
    "Good Will Hunting",  
    "Django Unchained",  
    "It's A Wonderful Life", 
    "Toy Story",  
    "Inglourious Basterds",  
    "Whiplash",  
    "2001: A Space Odyssey",  
    "Fight Club",  
    "Logan",  
    "The Shining",  
    "Carlito's Way",  
    "American Beauty", 
    "Star Wars: Episode IV", 
    "Rocky IV",  
    "Yojimbo",  
    "Star Wars: Episode V", 
    "Rocky III",  
    "The Thing",  
    "Rocky II",  
    "Indiana Jones and The Last Crusade",  
    "Prisoners",  
    "The Hurricane",  
    "Braveheart",  
    "One Flew Over the Cuckoo's Nest",  
    "Million Dollar Baby",  
    "Unforgiven",  
    "Vertigo",  
    "Misery",  
    "Chinatown",  
    "Dog Day Afternoon",  
    "Avengers: Infinity War",  
    "Léon: The Professional",  
    "Star Wars: Episode VI - Return of the Jedi",  
    "Parasite",  
    "Hot Fuzz",  
    "Kill Bill: Volume 1",  
    "The Game",  
    "City of God",  
    "Casino",  
    "The Intouchables",  
    "Birdman or (The Unexpected Virtue of Ignorance)",  
    "Rocky",  
    "Halloween",  
    "Close Encounters of the Third Kind",  
    "The Raid: Redemption",  
    "Deadpool",  
    "Nightcrawler",  
    "The Departed",  
    "Gran Torino",  
    "The Social Network",  
    "The Good, the Bad and the Ugly",  
    "Philadelphia",  
    "The Lord of the Rings: The Fellowship of the Ring", 
    "Die Hard with a Vengeance",  
    "Batman Begins",  
    "V for Vendetta",  
    "Full Metal Jacket",  
    "Planet of the Apes",  
    "Back to the Future",  
    "X-Men: Days of Future Past",  
    "Catch Me If You Can",  
    "Gone Girl",  
    "Donnie Darko",  
    "The Sixth Sense",  
    "The Lord of the Rings: The Two Towers",  
    "Predator",  
    "Spotlight",  
    "Ratatouille",  
    "X-Men: First Class",  
    "Toy Story 2",  
    "The Bourne Ultimatum",  
    "Heat",  
    "The Truman Show",  
    "The Prestige",  
    "Joker",  
    "The Last Samurai",  
    "Almost Famous",  
    "Dirty Harry",  
    "Magnum Force",  
    "Ocean's Eleven",  
    "Seven Samurai",  
    "Rambo: First Blood",
    "The Godfather: Part II",  
    "The Grand Budapest Hotel",  
    "Alien" 
  ]
  return list;
};

export default movieList;

  
